name: job concurrency
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy application
        run: |
          echo "deployment started"
          sleep 80
          echo "deployment finished...."